### ISSUE TITLE
Output "ERROR - could not deal with graph with rank H1(X,Z) < 3"

### ISSUE THREAD

**Issue by ChangwenXu98** [xiaohang007/SLICES#5]
Hi,

Thanks for the interesting work. I'm trying to generate slices with pymatgen structure as input. I noticed that in line 527 of `invcryrep.py`, it will print "ERROR - could not deal with graph with rank H1(X,Z) < 3". But that's not an error actually and I can still generate the corresponding slices. So I'm wondering why it matters to determine whether the rank of the graph is smaller than 3; even though a 3D embedding cannot be generated, I don't find such embeddings useful for building the slices representation. 

Looking forward to hearing from you!

**Comment by xiaohang007** [comment]
> Hi,
> 
> Thanks for the interesting work. I'm trying to generate slices with pymatgen structure as input. I noticed that in line 527 of `invcryrep.py`, it will print "ERROR - could not deal with graph with rank H1(X,Z) < 3". But that's not an error actually and I can still generate the corresponding slices. So I'm wondering why it matters to determine whether the rank of the graph is smaller than 3; even though a 3D embedding cannot be generated, I don't find such embeddings useful for building the slices representation.
> 
> Looking forward to hearing from you!

Thank you very much for your feedback. 
I have removed graph rank checks in invcryrep.py except that I added a graph_rank_check flag to check_SLICES function. 
This flag indicates whether to verify if a SLICES corresponds to a crystal graph with a rank H1(X,Z) < 3. The default value is True. It is advisable to set it to True for generative AI models and to False for property prediction AI models. In cases where the rank of H1(X,Z) in the graph is less than 3, it may not be possible to reconstruct this SLICES string to the original structure using SLI2Cry. This limitation stems from Eon's method's inability to generate a 3D embedding for a graph with a rank of H1(X,Z) less than 3. For example, if H1(X,Z)=2, then Eon's method can only create a 2D embedding for this graph. However, for property prediction AI models, this limitation is acceptable since reversibility is not required. 
I have updated both github repo and pypi  repo (v1.4.8), and you can install the lastest version of slices with pip to see the difference.

**Comment by ChangwenXu98** [comment]
Got it. Good to know. 
Thank you for the explanation and updates!
