### ISSUE TITLE
Not working with TMDCs

### ISSUE THREAD

**Issue by abdalazizrashid** [xiaohang007/SLICES#8]
I tried couple TMDCs (mp-1023936, mp-2815) and kept getting `TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'`

**Comment by xiaohang007** [comment]
Thank you for your interest in our work. The current decoding (reconstruction) algorithm of SLICES does not function for low-dimensional materials. This limitation arises because the initial step of our algorithm relies on Eon's graph theory method, which does not support low-dimensional crystal structures. Eon's method only works on fully-connected crystal graphs where the rank of translation vectors is not lower than 3. Transition metal dichalcogenides (TMDCs), being 2D materials, have a translation vector rank of 2 (<3), making it impossible to construct a 3D embedding using Eon's method. We are actively developing a SLICES decoding algorithm that will support low-dimensional materials. So, stay tuned.

**Comment by abdalazizrashid** [comment]
Thanks, appreciate your response
